name: Validate OWASP Entity Metadata

on:
  pull_request:
    paths:
      - '*.owasp.yaml'
  push:
    paths:
      - '*.owasp.yaml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

jobs:
  validate-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3

      - name: Validate Metadata File
        uses: owasp/nest-schema/.github/actions/validate@011b47d59567ae7cfd246948c67503ba2f6cc15b
